### ISSUE TITLE
Creating Pages via API

### ISSUE THREAD

**Issue by deecey** [DieSchittigs/contao-content-api-bundle#19]
Hi, thanks for developing the API! I am not sure if this is the right place, but I have a short question: is there a possibility to create pages initially via the API or is there perhaps another way to do it? I need to set up a Website and have to create many pages (about 250) with content (text, images, videos) that has already been written / created.
Regards, Chris

**Comment by Lixus** [comment]
Hi, creating pages is not really in the scope of this project - it just provides an API to allow a custom frontend with a Contao backend.

**Comment by deecey** [comment]
Ok thanks.
