### ISSUE TITLE
Contao Manager

### ISSUE THREAD

**Issue by stefansl** [DieSchittigs/contao-content-api-bundle#3]
Thank you for this extension! But it is not available in the Contao Manager. Maybe this helps: 
https://docs.contao.ninja/de/vortrag-composer-c3-c4-bundle.html#/

**Comment by saibotd** [comment]
I'm currently migrating the code into a Symfony Bundle. Is anything besides that necessary?

**Comment by saibotd** [comment]
Just looked into it. Content Api lib is installable via Contao Manager
